import app.utils.static_url as su
from app.utils.static_url import static_url


def test_hash_is_content_based_and_changes_with_content(tmp_path, monkeypatch):
    monkeypatch.setattr(su, "STATIC_DIR", tmp_path)
    su._cache.clear()
    f = tmp_path / "a.js"
    f.write_text("one")
    first = static_url("a.js")
    assert first.startswith("/static/a.js?v=") and len(first.split("=")[1]) == 10
    assert static_url("a.js") == first          # cached, stable
    f.write_text("two!")                        # changed content -> new URL
    second = static_url("a.js")
    assert second != first


def test_same_content_same_hash(tmp_path, monkeypatch):
    monkeypatch.setattr(su, "STATIC_DIR", tmp_path)
    su._cache.clear()
    (tmp_path / "a.js").write_text("same")
    (tmp_path / "b.js").write_text("same")
    assert static_url("a.js").split("=")[1] == static_url("b.js").split("=")[1]


def test_missing_file_and_path_escape_fall_back_unversioned(tmp_path, monkeypatch):
    monkeypatch.setattr(su, "STATIC_DIR", tmp_path / "static")
    (tmp_path / "static").mkdir()
    (tmp_path / "secret.txt").write_text("x")
    su._cache.clear()
    assert static_url("nope.js") == "/static/nope.js"
    assert static_url("../secret.txt") == "/static/../secret.txt"  # never hashed


async def test_plan_page_loads_the_hashed_plan_view(client):
    r = await client.get("/plan", headers={"Accept": "text/html"})
    assert r.status_code == 200
    expected = static_url("plan_view.js")
    assert f'<script src="{expected}"></script>' in r.text
    # the save row is static markup, not generated by the renderer
    assert 'id="ai-save-row"' in r.text and 'id="ai-regen-btn"' in r.text


async def test_shared_scripts_are_served(client):
    for name in ("plan_view.js", "sheet.js"):
        r = await client.get(f"/static/{name}")
        assert r.status_code == 200 and len(r.text) > 500
